services:
  task_manager:
    build:
      context: .
    environment:
      - SECRET_KEY=django-insecure-ktq$o_t&o$(478z9k4!#z!kdk#-7pq@4ed))8z=5w_xpsqdj5a
      - DB_NAME=task_manager
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - EMAIL_USER=test@mail.com
      - EMAIL_PORT=587
      - EMAIL_PASSWORD=test
      - DEFAULT_FROM_EMAIL=test@mail.com
      - RABBITMQ_USER=rmq
      - RABBITMQ_PASSWORD=rmq
    ports:
      - "8080:8000"
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./:/app/
    command: python /app/manage.py runserver 0.0.0.0:8000

  postgresql:
    build:
      context: ./postgresql/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5483:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: [ "CMD", "rabbitmqctl", "status" ]
