[tool.black]
line-length = 99
force-exclude = 'tasks/migrations/.*'

[tool.pytest.ini_options]
asyncio_mode = 'auto'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
known_first_party = 'task_manager'
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 99

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'E711']
max-line-length = 99
exclude = '*/migrations/*'
