# Generated by Django 4.2.4 on 2023-09-02 20:16

from django.db import migrations

from tasks.constants import SystemRole


def insert_roles(apps, schema_editor):
    Role = apps.get_model("tasks", "Role")
    for role in SystemRole:
        role_obj = Role(name=role)
        role_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_roles),
    ]
